openapi: 3.0.0
info:
  title: 'Selfdeclarations API'
  version: 1.0.0
  contact:
    name: David Valbuena
  license:
    name: Privative
paths:
  /api/v1/information-request:
    post:
      summary: InformationRequest
      requestBody:
        content:
          application/json:
            schema:
              properties:
                authorization:
                  type: object
                  properties:
                    username:
                      type: string
                      example: wG36MJpYEV
                  required:
                    - username
                requestId:
                  type: string
                  description: Identificador único de la solicitud creada
                  example: 50ac6c8e8a858efb8ffc2046c8232f718be4aade2930c2705efb8e8be8b0a6976284d1bf5fcafdd0
                locale:
                  type: string
                  example: es
              required:
                - authorization
                - requestId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "SUCCESS"
                    enum:
                      - SUCCESS
                      - FAILURE
                  reason:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: "Petición procesada correctamente"
                  requestId:
                    type: string
                    example: ab6671c7deea645b258ebc8ade753b7d2e9ca1938d1799582fbd7c9bb2cab917da7736fc50f6f1
                  request:
                    type: object
                    properties:
                      status:
                        type: string
                        example: "PENDING"
                        enum:
                          - SUCCESS
                          - PENDING
                          - FAILURE
                      type:
                        type: string
                        example: "ICA"
                      returnUrl:
                        type: string
                        example: "http://url-respuesta.com/autoliquidacion/pagos_pse_respuesta_pagos.php"
                      createdAt:
                        type: string
                        format: date-time
                        example: "2020-10-27T13:16:05.000000Z"
                      totalAmount:
                        type: number
                        example: 459000
                  company:
                    type: object
                    properties:
                      documentType:
                        type: string
                      document:
                        type: string
                      legalName:
                        type: string
                      commercialName:
                        type: string
                  income:
                    type: object
                    properties:
                      status:
                        type: string
                        example: "PAID"
                        enum:
                          - ACTIVE
                          - INACTIVE
                          - DRAFT
                          - PENDING_SIGN
                          - PDF_SENT
                          - PDF_MAX_ATTEMPS
                          - WITHOUT_PAY
                          - PAID
                          - PRESENTED
                          - CANCEL
                      signs:
                        type: number
                        description: Firmas requeridas para autorizar el documento.
                        minimum: 0
                        maximum: 2
                      numberSigns:
                        type: number
                        description: Firmas realizadas en el documento.
                        minimum: 0
                        maximum: 2
                      signers:
                        type: object
                        minItems: 1
                        properties:
                          documentType:
                            type: string
                          document:
                            type: string
                          bidderPosition:
                            type: string
                        required:
                          - documentType
                          - document
                          - bidderPosition
                  payment:
                    type: object
                    properties:
                      status:
                        type: string
                        example: "APPROVED"
                        enum:
                          - APPROVED
                          - PENDING
                          - DECLINED
                          - FAILED
                      description:
                        type: string
                      message:
                        type: string
                      paymentMethod:
                        type: string
                      paymentMethodName:
                        type: string
                      issuerName:
                        type: string
                      receipt:
                        type: string
                      authorizationCode:
                        type: string
                      currency:
                        type: string
                      totalPaid:
                        type: number
                      paidAt:
                        type: string
                        format: date-time
              examples:
                SUCCESS:
                  value:
                    status: SUCCESS
                    reason: 200
                    message: Petición procesada correctamente
                    requestId: ab6671c7deea645b258ebc8ade753b7d2e9ca1938d1799582fbd7c9bb2cab917da7736fc50f6f1
                    request:
                      status: PENDING
                      type: ICA
                      returnUrl: http://url-respuesta.com/autoliquidacion/pagos_pse_respuesta_pagos.php
                      createdAt: 2020-10-27T13:16:05.000000Z
                      totalAmount: 459000
                    company:
                      doumentType: NIT
                      doument: 6001903
                      lealName: Empresa Comercial
                      comercialName: PRUEBAS RECAUDO
                    income:
                      status: WITHOUT_PAY
                      signs: 1
                      numberSigns: 1
                      signers: [
                        {
                          documentType: CC,
                          document: 98237479,
                          bidderPosition: CEO,
                        }
                      ]
                    payment:
                      status: 1
                      description: Aprobado
                      message: Aprobada
                      paymentMethod: visa
                      paymentMethodName: Visa
                      issuerName: BANCO DE PRUEBAS
                      receipt: 1602771834
                      authorization: 000000
                      currency: COP
                      totalPaid: 1400000
                      paidAt: 2020-10-15 09:23:54
                FAILED:
                  value:
                    status: FAILED
                    reason: 404
                    message: La petición no es válida
                PENDING_SIGNATURE:
                  value:
                    status:
                      status: SUCCESS
                      reason: 200,
                      message: Petición procesada correctamente
                      requestId: 50ac6c8e8a858efb8ffc2046c8232f718be4aade2930c2705efb8e8be8b0a6976284d1bf5fcafdd0
                      request:
                        status: PENDING
                        type: CONSUMER_BEER
                        returnUrl: https://aqui.regresa.al/terminar-proceso
                        createdAt: 2017-07-17 10:50:27
                        totalAmount: 790684000
                      company:
                        documentType: NIT
                        document: 900299228
                        legalName: Development
                        commercialName: Testing
                      income:
                        status: PENDING_SIGN
                        signs: 2
                        numberSigns: 0
                        signers: [ ]
                      payment: [ ]
