name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npx sst deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CERT_ARN: ${{ vars.AWS_CERT_ARN }}
          APP_DOMAIN_NAME: ${{ vars.APP_DOMAIN_NAME }}
          NEXT_PUBLIC_FEEDBACK_FORM_URL: ${{ vars.NEXT_PUBLIC_FEEDBACK_FORM_URL }}
